services:
  nextjs-app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: >
      sh -c "
        until nc -z postgres 5432; do
          echo 'Waiting for PostgreSQL...';
          sleep 1;
        done;
        echo 'PostgreSQL is up';
        npm install &&
        npx prisma db push &&
        npx prisma generate &&
        npm run build &&
        npm run start
      "

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: