services:
  nextjs-app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
    command: >
      sh -c "
        npx prisma db push
        npm run build
        npm run start
      "

networks:
  app-network:
    driver: bridge